Q 1) Given three integer arrays arr1, arr2 and arr3 sorted in strictly increasing order, return a sorted array of only the integers that appeared in all three arrays.

sol.

In [1]:
arr1 = [1,2,3,4,5]
arr2 = [1,2,5,7,9]
arr3 = [1,3,4,5,8]
ans = []
for i in arr1:
    if i in arr2 and i in arr3:
        ans.append(i)
print(ans)

[1, 5]


Q.2 Given two **0-indexed** integer arrays nums1 and nums2, return *a list* answer *of size* 2 *where:*

- answer[0] *is a list of all **distinct** integers in* nums1 *which are **not** present in* nums2*.*
- answer[1] *is a list of all **distinct** integers in* nums2 *which are **not** present in* nums1.

sol.

In [2]:
nums1 = [1,2,3]
nums2 = [2,4,6]
number1 = []
number2 = []
for i in nums1:
    if i not in nums2:
        number1.append(i)
for j in nums2:
    if j not in nums1:
        number2.append(j)
print([number1,number2])

[[1, 3], [4, 6]]


Q.3)Given a 2D integer array matrix, return *the **transpose** of* matrix.

The **transpose** of a matrix is the matrix flipped over its main diagonal, switching the matrix's row and column indices.

sol.

In [26]:
# method -1 using numpy
import numpy as np 
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix = np.array(matrix)
print(matrix.T)

# method -2 without numpy
matrix = [[1,2,3],[4,5,6],[7,8,9]]
res = []
n = len(matrix[0])
for i in range(n):
    res.append([row[i] for row in matrix])
print(res)


[[1 4 7]
 [2 5 8]
 [3 6 9]]
3
[[1, 4, 7], [2, 5, 8], [3, 6, 9]]


Q.4) Given an integer array nums of 2n integers, group these integers into n pairs (a1, b1), (a2, b2), ..., (an, bn) such that the sum of min(ai, bi) for all i is maximized. Return the maximized sum.

sol. 

In [33]:
nums = [1,4,3,2]
n = len(nums)
nums.sort()
total = 0
for i in range(0,n,2):
    total += min(nums[i],nums[i+1])
print(total)

4


Q.5) You have n coins and you want to build a staircase with these coins. The staircase consists of k rows where the ith row has exactly i coins. The last row of the staircase **may be** incomplete.

Given the integer n, return *the number of **complete rows** of the staircase you will build*.

In [40]:
n = 5
count = 0
i=0
while n>=0:
    i+=1
    n=n-i
print(i-1)

2


Q.6) Given an integer array nums sorted in non-decreasing order, return an array of the squares of each number sorted in non-decreasing order.

sol.

In [41]:
nums = [-4,-1,0,3,10]
for i in range(len(nums)):
    nums[i] = nums[i]**2
nums.sort()
print(nums)

[0, 1, 9, 16, 100]


Q.7)You are given an m x n matrix M initialized with all 0's and an array of operations ops, where ops[i] = [ai, bi] means M[x][y] should be incremented by one for all 0 <= x < ai and 0 <= y < bi.

Count and return *the number of maximum integers in the matrix after performing all the operations*

sol.

In [58]:
def maxCount(m,n,ops):
    length = len(ops)
    if length == 0:
        return m*n
    result = [ops[0][0] , ops[0][1]]
    for i in range(1,length):
        result[0] = min(result[0] , ops[i][0])
        result[1] = min(result[1] , ops[i][1])
    return result[0]*result[1]     
m = 3
n = 3
ops = [[2,2],[3,3]]
print(maxCount(m,n,ops))


SyntaxError: invalid syntax (143045532.py, line 13)

Q.8) Given the array nums consisting of 2n elements in the form [x1,x2,...,xn,y1,y2,...,yn].

*Return the array in the form* [x1,y1,x2,y2,...,xn,yn].

In [57]:
nums = [2,5,1,3,4,7]
n = 3
new_array=[0]*(2*n)
for i in range(0,n):
    new_array[2*i],new_array[2*i+1]=nums[i],nums[i+n]
print(new_array)


[2, 3, 5, 4, 1, 7]
