creating a numpy array ->
1) various numbers of ranks 
2) defining size of the array
3) various data types (list,tuple)



In [11]:
import numpy as np
# using tuple
arr = np.array((1,2,3))
print(arr)
# using list
arr2 = np.array([1,2,3])
print(arr2)
# using by rank 
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3)
print("###############################s")
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
# row and column ::2 alternative column for row :2 we used
sliced_arr = arr[:2,::2]
print(sliced_arr)
# index of arr (1,3),(1,2),(0,1),(3,0)
Index_arr = arr[[1, 1, 0, 3], 
                [3, 2, 1, 0]]
print(Index_arr)

[1 2 3]
[1 2 3]
[[1 2 3]
 [4 5 6]]
###############################s
[[-1.  0.]
 [ 4.  6.]]
[0. 6. 2. 3.]


Basic Array Operations

In [18]:
import numpy as np
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[4, 3],
              [2, 1]])
print(a)
# for adding in every element
print(a+1)
# sum of every elements 
print(a.sum())
# sum of two array 
print(a+b)

[[1 2]
 [3 4]]
[[2 3]
 [4 5]]
10
[[5 5]
 [5 5]]


Data types in numpy-->
1) Every Numpy array is a table of elements (usually numbers), all of the same type.
2) indexed by a tuple of positive integers.
3)  Every ndarray has an associated data type (dtype) object.
4) 

In [29]:
import numpy as np
res = np.array([1,2,3])
print(res.dtype)

arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64)
# adding two arrays
res = np.add(arr1,arr2)
res = sum(res)
print(sum(res))

int32
38.0


Methods in Numpy

In [81]:
import numpy as np
# arange 
print(np.arange(4).reshape(2,2))
print(np.arange(1,2,0.1))

# dot 
print(np.dot(5+2j,4+3j))

# place function
ar = np.arange(12).reshape(3,4)
print(ar)
# place 
np.place(ar, ar > 10, [15, 25, 35])
print(ar)

# absolute
print(np.absolute(ar))

# insert 
arr = np.arange(12).reshape(3,4)
# print(arr)
# np.insert(arr,1,9,axis=1)
print("###########")
a = np.insert(arr, [1],[[1],[2],[3]], axis = 1)
print(a)

# deletion

new_array= np.delete(a,0,0)
print(new_array)

new = np.empty(2,dtype=int)
print(new)
new_array_2 =  np.array([[1,2],[3,4]])
# convert 2d into 1d array
print(new_array_2.flatten())
print(type(new_array_2))

[[0 1]
 [2 3]]
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
(14+23j)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 15]]
###########
[[ 0  1  1  2  3]
 [ 4  2  5  6  7]
 [ 8  3  9 10 11]]
[[ 4  2  5  6  7]
 [ 8  3  9 10 11]]
[1717986922 1073636966]
[1 2 3 4]
<class 'numpy.ndarray'>


make array with zeros


In [83]:
import numpy as np

a = np.zeros(9,dtype=int)
print(a)

[0 0 0 0 0 0 0 0 0]
